from model.keypoint_classifier.keypoint_classifier import KeyPointClassifier
from model.point_history_classifier.point_history_classifier import PointHistoryClassifier
from model.keypoint_classifier_left.keypoint_classifier_left import KeyPointClassifierLeft